FROM ubuntu:20.04
EXPOSE 8889
SHELL ["/bin/bash", "--login", "-c"]
RUN apt update && apt-get -y install build-essential wget git vim
RUN apt-get -y install build-essential
#RUN echo '2\n85\n1\n1\n' | apt-get -y install libxml2-dev
WORKDIR /opt
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh
RUN bash Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p /root/miniconda
ENV PATH="/root/miniconda/bin:${PATH}" LD_LIBRARY_PATH="/usr/local/lib"
ARG PATH="/root/miniconda/bin:${PATH}"
RUN eval "$(conda shell.bash hook)" \
    && conda init bash \
    && conda create -y --name nmt \
    && conda activate nmt\
    && conda install -y pytorch==1.6.0 torchvision==0.7.0 cpuonly -c pytorch\
    && conda install -y -c pytorch torchtext=0.7.0\
    && conda install -y -c conda-forge configargparse=1.5.3\
    && conda install -y -c conda-forge flask=2.0.2\
    && conda install -y -c conda-forge waitress=2.0.0
WORKDIR /root
RUN git clone https://github.com/jsc723/gl-nmt.git
COPY brnn3_5_step_20000.pt /root/gl-nmt/available_models
COPY conf.json /root/gl-nmt/available_models
RUN wget http://www.phontron.com/kytea/download/kytea-0.4.7.tar.gz
RUN tar -xzf kytea-0.4.7.tar.gz
WORKDIR /root/kytea-0.4.7/
RUN chmod +x configure
RUN ./configure
RUN make && make install
WORKDIR /root/gl-nmt
CMD ["conda", "run", "--no-capture-output", "-n", "nmt", "python", "/root/gl-nmt/server.py", "--port", "8889"]
